version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTIC_VERSION:-6.7.0}
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=es-cluster"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "node.master=true"
      - "node.data=true"
      - "node.ingest=true"
      - "node.name=es-node.{{.Task.Slot}}.{{.Node.Hostname}}"
      - "LOGSPOUT=ignore"
    networks:
       - esnet
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:${ELASTIC_VERSION:-6.7.0}
    environment:
      - LOGSPOUT=ignore
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - esnet
    configs:
      - source: ls_config
        target: /usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ELASTIC_VERSION:-6.7.0}
    networks:
      - esnet
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    environment:
      - SERVER_NAME=kibana.${DOMAIN:-localhost}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_HOST:-http://elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST:-http://elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      - LOGSPOUT=ignore
    deploy:
      mode: replicated
      replicas: 1

  logspout:
    image: ruanbekker/logspout-logstash:v3.2.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ROUTE_URIS=logstash+tcp://logstash:5000
    networks:
      - esnet
    deploy:
      mode: global

  webapp:
    image: nginx
    networks:
      - esnet
    environment:
      - LOGSTASH_TAGS=docker,production
      - LOGSTASH_FIELDS=service_name={{.Service.Name}},task.id={{.Task.ID}}
      - DOCKER_LABELS=""
    ports:
      - 8082:80
    labels:
      com.example.lekke: "yes this is lekke"
    deploy:
      labels:
        com.example.description: "this is spartaaaa"

networks:
  esnet:
    driver: overlay

configs:
  ls_config:
    file: $PWD/logstash/config/logstash.conf
